Tourism_strategy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
import xadmin

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('', include('home.urls')),
    path('', include('captcha.urls')),
    path('', include('ckeditor_uploader.urls')),
    path('', include('area_picker.urls'))
]
static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static,serve
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('hot', views.hot, name='hot'),
    path('recommend', views.recommend, name='recommend'),
    path('login', views.login_page, name='login'),
    path('person/<tab>', views.person_page, name='person'),
    path('anotherone/<int:id>/<tab>', views.anotherone_page, name='anotherone'),
    path('detail/<int:strategy_id>', views.detail_page, name='detail'),
    path('edit', views.edit_page, name='edit'),
    path('change', views.change, name='change'),
    path('logout', views.logout_page, name='logout'),
    path('register', views.register_page, name='register'),
    path('write', views.write_page, name='write'),
    path('like', views.like_strategy, name='like'),
    path('collection', views.collection_strategy, name='collection'),
    path('comment', views.comment, name='comment'),
    path('send_chat', views.send_chat, name='send_chat'),
    path('open_chat', views.open_chat, name='open_chat'),
    path('del_chat', views.del_chat, name='del_chat'),
    path('open_dialog/<int:id>', views.open_dialog, name='open_dialog'),
    path('follow', views.follow, name='follow'),
    path('unfollow', views.unfollow, name='unfollow'),
    path('report', views.report, name='report'),
    path('search', views.search, name='search')
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone
from stdimage.models import StdImageField
from stdimage.utils import UploadToUUID
from ckeditor_uploader.fields import RichTextUploadingField


class Tags(models.Model):
    tag_name = models.CharField(max_length=50, verbose_name='标签名')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'

    def __str__(self):
        return self.tag_name


class User(models.Model):
    """普通用户表"""

    gender = (
        ('male', '男'),
        ('female', '女'),

    )

    username = models.CharField(max_length=128, verbose_name="用户名",  unique=True)
    password = models.CharField(max_length=256, verbose_name="密码")
    phone = models.CharField(
        max_length=13,
        verbose_name="手机号",
        blank=True
    )
    email = models.EmailField(blank=True, verbose_name="邮箱")
    sex = models.CharField(max_length=32, choices=gender, default='男', verbose_name="性别", blank=True)
    avatar = StdImageField(
        upload_to=UploadToUUID(path=datetime.now().strftime("avatar/%Y%m%d")),
        variations={'thumbnail': {'width': 100, 'height': 75, 'style': 'objects-fit:cover'}},
        null=True,
        blank=True,
        verbose_name="头像"
    )
    background = StdImageField(
        upload_to=UploadToUUID(path=datetime.now().strftime("background/%Y%m%d")),
        variations={'thumbnail': {'width': 100, 'height': 75}},
        null=True,
        blank=True,
        verbose_name="背景图"
    )
    sign = models.CharField(max_length=64, null=True, blank=True, verbose_name="一句话介绍", default='该用户还没有个性签名')
    introduce = models.CharField(max_length=200, null=True, blank=True, verbose_name="个人简介", default='该用户还没有个人简介')
    c_time = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tags, related_name='user_pick', blank=True)

    def avatar_img(self):
        if self.avatar:
            return str('<img src="%s" width="60" height="60" style="object-fit: cover" />' % self.avatar.url)
        else:
            return ' '

    avatar_img.short_description = '头像'
    avatar_img.allow_tags = True

    def background_img(self):
        if self.background:
            return str('<img src="%s" width="200" height="48"  style="object-fit:cover"/>' % self.background.url)
        else:
            return ' '

    background_img.short_description = '背景图'
    background_img.allow_tags = True

    def __str__(self):
        return self.username

    class Meta:
        ordering = ['c_time']
        verbose_name = '旅途用户'
        verbose_name_plural = '旅途用户'


class Strategy(models.Model):
    state = (
        ('review', '审核中'),
        ('publish', '已发布'),
        ('nopass', '建议修改')
    )
    title = models.CharField(max_length=100, blank=True)
    content = RichTextUploadingField(verbose_name='攻略', default=None, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    img = StdImageField(
        upload_to=UploadToUUID(path=datetime.now().strftime("strategy/%Y%m%d")),
        variations={'thumbnail': {'width': 160, 'height': 100}},
        null=True,
        blank=True,
        verbose_name="题图"
    )
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    s_state = models.CharField(max_length=32, choices=state, default='审核中', verbose_name="攻略状态", blank=True)
    users_like_count = models.IntegerField(blank=True, verbose_name="点赞数", default=0)
    users_like = models.ManyToManyField(User, related_name="strategy_like", blank=True)
    collections_count = models.IntegerField(blank=True, verbose_name="收藏数", default=0)
    collections = models.ManyToManyField(User, related_name="strategy_collections", blank=True)
    comment_count = models.IntegerField(blank=True, verbose_name="点赞数", default=0)
    tags = models.ManyToManyField(Tags, related_name='strategy_pick', blank=True)

    def strategy_img(self):
        if self.img:
            return str('<img src="%s" width="60" height="60" style="object-fit: cover" />' % self.img.url)
        else:
            return ' '

    strategy_img.short_description = '头像'
    strategy_img.allow_tags = True

    class Meta:
        ordering = ("title", )
        verbose_name = '攻略文章'
        verbose_name_plural = '攻略文章'

    def __str__(self):
        return self.title


class Comment(models.Model):#同一个model引用两个外键必须要指定不同的related_name
    """
    评论功能
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='评论者', related_name="comment_author")
    content = models.CharField(max_length=300, verbose_name='评论内容')
    to_someone = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='回复某人', null=True, related_name="comment_to")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE, verbose_name='攻略')

    class Meta:
        verbose_name = '评论攻略'
        verbose_name_plural = '评论攻略'

    def __str__(self):
        return self.content[:10]


class New(models.Model):#同一个model引用两个外键必须要指定不同的related_name
    """
    新私信提醒
    """
    status = {
        ('nomal', '正常'),
        ('black', '屏蔽'),
    }
    new_send_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='发送者', related_name="new_send_user")
    content = models.CharField(max_length=300, verbose_name='私信内容')
    new_to_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='回复某人',
                                null=True, related_name="new_to_user")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    pull_black = models.CharField(max_length=32, choices=status, default='正常', verbose_name="状态", blank=True)

    class Meta:
        verbose_name = '新私信'
        verbose_name_plural = '新私信'

    def __str__(self):
        return self.content[:10]


class Chat(models.Model):#同一个model引用两个外键必须要指定不同的related_name
    """
    私信
    """
    status = {
        ('nomal', '正常'),
        ('black', '屏蔽'),
    }
    send_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='发送者', related_name="send_user")
    content = models.CharField(max_length=300, verbose_name='私信内容')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='回复某人', null=True, related_name="to_user")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    pull_black = models.CharField(max_length=32, choices=status, default='正常', verbose_name="状态", blank=True)

    class Meta:
        verbose_name = '私信'
        verbose_name_plural = '私信'

    def __str__(self):
        return self.content[:10]


class Follow(models.Model):
    follow = models.ForeignKey(User, related_name='follow_user', on_delete=models.CASCADE)
    fan = models.ForeignKey(User, related_name='fan_user', on_delete=models.CASCADE)

    def __str__(self):
        return "follow:{},fan:{}".format(self.follow, self.fan)


class Report(models.Model):
    """
    举报表
    """
    item = (
        ('spam', '垃圾信息'),
        ('unfriendly', '不友善信息'),
        ('harm', '有害信息'),
        ('tort', '涉嫌侵权'),
        ('other', '其他'),
    )
    target = models.ForeignKey(User, verbose_name='目标', related_name='target', on_delete=models.CASCADE)
    report = models.ForeignKey(User, verbose_name='举报者', blank=True, null=True, related_name='report', on_delete=models.CASCADE)
    reason = models.CharField(max_length=32, choices=item, default='男', verbose_name="性别", blank=True)
    details = models.CharField(max_length=500, blank=True, null=True)
    lock_time = models.DateTimeField(verbose_name='开始封禁时间', blank=True, null=True)
    unlock_time = models.DateTimeField(verbose_name='解除封禁时间', blank=True, null=True)

    class Meta:
        verbose_name = '封禁'
        verbose_name_plural = '封禁'

    def __str__(self):
        return self.reason

home/templates/home/register_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>旅游攻略系统</title>
    <!-- 优先使用 IE 最新版本和 Chrome -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <!-- 启用360浏览器的极速模式(webkit) -->
    <meta name="renderer" content="webkit">
    <meta name="keywords" content="旅游攻略">
    <meta name="description" content="旅游攻略系统是展示旅游攻略的网站">
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/login.css' %}">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="{% static 'home/js/jquery.min.js' %}"></script>
</head>
<body>
<div class="content"><!--注册页面主体-->
  <div class="Card login-box" style="overflow: visible;">
    <div style="padding:30px 0 5px 0;display: block;">
      <h1>旅途</h1>
      <div style="margin-top: 15px;color:#0084ff;font-size: 22px;">注册旅途，带你走遍这个世界</div>
    </div>
    <div id="register" style="position: relative;">
      <div style="padding: 0 40px 36px;">
          <div class="account" style="margin-top: 16px;border-bottom: 1px solid #ebebeb;border-radius: 0;">
            <div style="display: inline-block;float: left;min-width: 72px;transform: translateY(4px);"></div>
            <div style="overflow: hidden;position: relative;">
              <div style="width: auto;height: 48px;padding: 0;color:#8590a6;border-radius: 0;">
                <!--<input type="text" name="username" maxlength="150" class="Input" placeholder="用户名" value="">-->
                {{ register_form.username }}
              </div>
              <div class="errorMask" style="width: 0;height: 0;padding:0;margin: 0;opacity: 0;">
                {% if login_form.captcha.errors %}
                  <div class="errorMask">验证码错误</div>
                {% else %}
                  {% if message %}
                    <div class="errorMask">{{ message }}</div>
                  {% endif %}
                {% endif %}
              </div>
            </div>
          </div>
          <div class="password">
            <div style="position: relative;">
              <div style="width: 100%;height: 48px;padding: 0;color: #8590a6;border: none;border-radius: 0;box-sizing: border-box;transition: background .2s,border .2s;">
                <!--<input type="password" name="password1" class="Input" placeholder="密码" value="">-->
                {{ register_form.password1 }}
              </div>
            </div>
          </div>
          <div class="password">
            <div style="position: relative;">
              <div style="width: 100%;height: 48px;padding: 0;color: #8590a6;border: none;border-radius: 0;box-sizing: border-box;transition: background .2s,border .2s;">
                <!--<input type="password" name="password2" class="Input" placeholder="确认密码" value="">-->
                {{ register_form.password2 }}
              </div>
            </div>
          </div>
          <div class="password">
            <div style="position: relative;">
              <div style="width: 100%;height: 48px;padding: 0;color: #8590a6;border: none;border-radius: 0;box-sizing: border-box;transition: background .2s,border .2s;">
                <!--<input type="password" name="password2" class="Input" placeholder="确认密码" value="">-->
                {{ register_form.phone }}
              </div>
            </div>
          </div>
          <div class="password">
            <div style="position: relative;">
              <div style="width: 100%;height: 48px;padding: 12px 0 0 8px;color: #8590a6;border: none;border-radius: 0;box-sizing: border-box;transition: background .2s,border .2s;text-align: left">
                <!--<input type="password" name="password2" class="Input" placeholder="确认密码" value="">-->
                {{ register_form.sex.label_tag }}
                {{ register_form.sex }}
              </div>
            </div>
          </div>
          <div class="password">
            <div style="position: relative;">
              <div style="width: 100%;height: 48px;padding: 12px 0 0 8px;color: #8590a6;border: none;border-radius: 0;box-sizing: border-box;transition: background .2s,border .2s;text-align: left">
                <!--<input type="password" name="password2" class="Input" placeholder="确认密码" value="">-->
                <label for="">旅游爱好：</label>
                <span id="tags" class="tags-picked"></span>
                <button id="plus_tag" class="select-btn" data-toggle="modal" data-target="#myModal">
                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
                <button id="minus_tag" class="select-btn" data-toggle="modal" data-target="#myModal2">
                  <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                </button>
              </div>
            </div>
          </div>
          <!--<div class="password">
            <div style="position: relative;">
              <div style="width: 100%;height: 48px;padding: 5px 0 0 8px;color: #8590a6;border: none;border-radius: 0;box-sizing: border-box;transition: background .2s,border .2s;text-align: left">
                <input type="password" name="password2" class="Input" placeholder="确认密码" value="">
                {{ register_form.captcha.label_tag }}
                {{ register_form.captcha }}
              </div>
            </div>
          </div>-->
          <div class="login-options">
          </div>
          <button class="submitButton button-blue" id="register_btn">注册</button>
      </div>
      <div class="SignContainer-switch">
        已有账号？<span onclick="login()">登录</span>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog"  style="width: 400px;margin: 300px auto;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">选择旅游爱好</h4>
            </div>
            <div class="modal-body">
              {% for item in tag %}
                <button class="tag-item" value="{{ item.id }}">{{ item.tag_name }}</button>
              {% endfor %}
            </div>
            <div class="modal-footer">
                <!--<button type="button" class="btn btn-default">关闭</button>-->
                <button type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog"  style="width: 400px;margin: 300px auto;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">选择旅游爱好</h4>
            </div>
            <div class="modal-body">
              {% for item in tag %}
                <button class="tag-item-minus" value="{{ item.id }}">{{ item.tag_name }}</button>
              {% endfor %}
            </div>
            <div class="modal-footer">
                <!--<button type="button" class="btn btn-default">关闭</button>-->
                <button type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>
</body>
  <script type="text/javascript">
    function login() {
      $(location).attr('href', 'login');
    }
    $(function () {
      var tags=[];
      var tags_name=[];
      $('.tag-item').click(function () {
        if ($.inArray($(this).val(),tags)==-1 && tags.length<=8){
          tags.push($(this).val());
          tags_name.push($(this).text());
          console.log('1',tags_name,tags)
          $('#tags').text(tags_name)
        }else if ($.inArray($(this).val(),tags)==-1 && tags.length>8){
          alert('最多添加九个爱好')
        }
      });
      $('.tag-item-minus').click(function () {
        if ($.inArray($(this).val(),tags)!=-1){
          tags.splice($.inArray($(this).val(),tags),1);
          tags_name.splice($.inArray($(this).val(),tags_name),1);
          console.log('1',tags_name)
          $('#tags').text(tags_name)

        }
      });
      $('#minus_tag').click(function () {

      });
      $('#register_btn').click(function () {
        console.log('数据', $('#id_sex').val());
        $.ajax({
          cache:false,
          type:"POST",
          url:'{% url 'register' %}',
          async:true,
          traditional: true,
          data:{
            username:$('#id_username').val(),
            password1:$('#id_password1').val(),
            password2:$('#id_password2').val(),
            phone:$('#id_phone').val(),
            sex:$('#id_sex').val(),
            tags:tags
           },
          success:function (result) {
            console.log('re', result.status);
          },

        })
      })
    })
  </script>

  <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
  <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
</html>

home/templates/home/write_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>旅游攻略系统</title>
  <!-- 优先使用 IE 最新版本和 Chrome -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <!-- 启用360浏览器的极速模式(webkit) -->
  <meta name="renderer" content="webkit">
  <meta name="keywords" content="旅游攻略">
  <meta name="description" content="旅游攻略系统是展示旅游攻略的网站">
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/font-awesome.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/app.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/toastr.min.css' %}">
  <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
  <script src="{% static 'home/js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
  <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
  <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'home/js/toastr.min.js' %}"></script>
  <script type="text/javascript">
         toastr.options.positionClass = 'toast-top-center';
  </script>
</head>
<body>
<form action="" method="POST" name="strategy" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="navbar">
    <div class="navbar-logo">
      <a href="/">
        <div class="logo-text">旅</div>
      </a>
    </div>
    <div class="navbar-title">
      <div style="font-weight: bolder">写攻略</div>
    </div>
    <div class="navbar-functionality">
      <div class="publish">
        <div class="publish-button" id="publish_btn" style="cursor: pointer;"><span>发布</span><span class="caret"></span></div>
      </div>
      <div class="dropdown" style="display: flex;flex-direction: row;align-items: center">
        <a href="" style="font-size: 16px;color: #b3b3b3;padding: 4px 16px;" class="dropdown-toggle"
           data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-menu-hamburger"></span>
        </a>
        <ul class="dropdown-menu" style="left: -20px;">
          <li><a href="#">我的文章</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="img-box" onclick="$('#id_img').click()">
      <label for="" class="cli-hide">
        <svg class="Zi Zi--Camera WriteCover-uploadIcon" fill="currentColor" viewBox="0 0 24 24" width="42" height="42"><path d="M20.094 6S22 6 22 8v10.017S22 20 19 20H4.036S2 20 2 18V7.967S2 6 4 6h3s1-2 2-2h6c1 0 2 2 2 2h3.094zM12 16a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7zm0 1.5a5 5 0 1 0-.001-10.001A5 5 0 0 0 12 17.5zm7.5-8a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" fill-rule="evenodd"></path>
        </svg>
      </label>
      <span style="font-size: 18px;" class="cli-hide">添加题图</span>
      <div id="image-holder"></div>
    </div>
    {{ write_form.img }}
    {{ write_form.title }}
    {{ write_form.content }}
    <span>{{ message }}</span>
  </div>
</form>
</body>
<script type="text/javascript">
  function index() {
    $(location).attr('href', 'index');
  }
  function pub() {
    var len = $("#id_title").val().length
    var content = CKEDITOR.instances.id_content.document.getBody().getText().length
    if (len >= 5 && content >= 10) {
      document.strategy.submit()
    } else {
      alert("发布失败，标题少于5个字或内容少于10个字")
    }
  }
  $(function () {
    $('#id_img').on('change', function () {
      if (typeof(FileReader) != "undfined") {
        var image_holder = $('#image-holder');
        image_holder.empty();
        var reader = new FileReader();
        reader.onload = function (e) {
          $("<img />", {
            "src": e.target.result,
            "class": "img-read"
          }).appendTo(image_holder);
          $(".cli-hide").hide()
        };
        image_holder.show();
        reader.readAsDataURL($(this)[0].files[0]);
      } else {
        alert('你的浏览器不支持FileReader.');
      }
    });
    $("#publish_btn").click(function () {
      var len = $("#id_title").val().length;
      var content = CKEDITOR.instances.id_content.document.getBody().getText().length;
      if (len >= 3 && content >= 10) {
        document.strategy.submit();
{#        $.ajax({#}
{#          cache: false,#}
{#          type: "POST",#}
{#          url: '{% url 'write' %}',#}
{#          async: true,#}
{#          processData: false,#}
{#          contentType: false,#}
{#          data: $('#strategy').serialize(),#}
{#          success: function (result) {#}
{#            console.log('re', result.status);#}
{#            window.location.reload()#}
{#          }#}
{#        })#}
      } else {
        alert("发布失败，标题少于3个字或内容少于10个字")
      }
    })
  })
</script>

</html>